### ISSUE TITLE
Enter to Hit Next Level

### ISSUE THREAD

**Issue by AJ213** [noahkra/ClustertruckSpeedrunMod#2]
**Describe the feature you'd like to request.**
Keybind to hit next level

**Give reasoning on why this feature is needed.**
I hate using my mouse

**Additional context**
I hate using my mouse

**Comment by AJ213** [comment]
can you also make the option to keep cursor locked too here? Although that means there should be keybinds to exit to menu and restart. A proper game like Freight Hopper does that.

**Comment by noahkra** [comment]
should probably be rebindable

**Comment by noahkra** [comment]
Added in v1.3.0. not rebindable for now lol

**Comment by noahkra** [comment]
Feature removed in v1.4.0 as it was sadly too buggy and inconsistent.
