### ISSUE TITLE
Dying Keep Cursor Locked

### ISSUE THREAD

**Issue by AJ213** [noahkra/ClustertruckSpeedrunMod#4]
**Describe the feature you'd like to request.**
My cursor is running away from me and then closing the game when I die because I lack skill and have 3 monitors

**Give reasoning on why this feature is needed.**
So I can record a full game run without minimizing clustertruck

**Additional context**
I would honestly love if I could do an entire run without my cursor showing and escaping but that may be too much to ask. But I am also a poor linux user who can't make this themselves unless I do something crazy like run an IDE under Proton. Maybe...

**Comment by noahkra** [comment]
Added in 1.1.0 :)
