### ISSUE TITLE
unban levels besides 4:5 for randomizer

### ISSUE THREAD

**Issue by AJ213** [noahkra/ClustertruckSpeedrunMod#6]
**Describe the feature you'd like to request.**
only ban 4:5 for Randomizer truckflip

**Give reasoning on why this feature is needed.**
8:6, 8:10 and 9:10 are all doable normally. Verified by me, TF, and Wolfii

**Additional context**
8:6 you jump instantly when you land on the trucks that get shot up
9:10 when you jump most of the time the truck gets sent off the map rather than into other trucks
8:10 you can jump before the pipes so that they get stuck allowing you to beat the level

Supertruck doesn't make much a difference either for these levels except for 8:10 being a bit harder, but you can move left-right to make levels more normal.

**Comment by noahkra** [comment]
I would like to make sure it is also possible when the runner is less experienced, if less experienced runners can do it I'm on board for removing them from the ban list

**Comment by noahkra** [comment]
Added in v1.2.2, including 4:5
