### ISSUE TITLE
1.2.0 and 1.2.1 Override "By Levels" setting to "By World"

### ISSUE THREAD

**Issue by roninpawn** [noahkra/ClustertruckSpeedrunMod#7]
**The Issue**
Copy/pasting 1.2.x files overtop the old remembers all my settings except the "By Levels" selection for the Autosplitter. In both versions, (including upgrading from 1.2.0 to 1.2.1) it defaults me back to "By World," but while remembering all other settings, including that I had 'Reset in Menu' ticked.

**To Reproduce**
Install a pre 1.2.1 version and configure the autosplitter to split 'By Levels.'
Install a later version overtop the old, and open the program.
You'll see that it has defaulted back to 'By Worlds.'

**Screenshots**
First time opening 1.2.1
![image](https://github.com/noahkra/ClustertruckSpeedrunMod/assets/49294050/76f2a5a3-4d78-4e9b-8451-291c4e987aa8)

**Additional context**
I'll add the note that 1.2.0 also forgot where the Clustertruck directory was. But we know that to be a one-time issue that came with a change in how the UI is implemented. And installing 1.2.1, the directory was carried over correctly. (noting it here for search relevance -- to avoid questions about it in future)

**Comment by noahkra** [comment]
Fixed in v1.2.2
